#ifndef CLIENT_H
#define CLIENT_H
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#define CLIENT_TITLE_SERVERADDR "serveraddr"
#define CLIENT_TITLE_SERVERADDR_LEN strlen(CLIENT_TITLE_SERVERADDR)
#define CLIENT_TITLE_SERVERPORT "serverport"
#define CLIENT_TITLE_SERVERPORT_LEN strlen(CLIENT_TITLE_SERVERPORT)
#define CLIENT_TITLE_PROXY  "proxies"
#define CLIENT_TITLE_PROXY_LEN  strlen(CLIENT_TITLE_PROXY)
#define CLIENT_TITLE_NAME   "name"
#define CLIENT_TITLE_NAME_LEN   strlen(CLIENT_TITLE_NAME)
#define CLIENT_TITLE_TYPE   "type"
#define CLIENT_TITLE_TYPE_LEN   strlen(CLIENT_TITLE_TYPE)
#define CLIENT_TITLE_LOCALIP    "localip"
#define CLIENT_TITLE_LOCALIP_LEN    strlen(CLIENT_TITLE_LOCALIP)
#define CLIENT_TITLE_LOCALPORT  "localport"
#define CLIENT_TITLE_LOCALPORT_LEN  strlen(CLIENT_TITLE_LOCALPORT)
#define CLIENT_TITLE_REMOTEPORT "remoteport"
#define CLIENT_TITLE_REMOTEPORT_LEN strlen(CLIENT_TITLE_REMOTEPORT)
typedef enum CLIENT_TITLE_E {
    CLI_TITLE_SERVERADDR=0,
    CLI_TITLE_SERVERPORT,
    CLI_TITLE_PROXY,
    CLI_TITLE_NAME,
    CLI_TITLE_TYPE,
    CLI_TITLE_LOCALIP,
    CLI_TITLE_LOCALPORT,
    CLI_TITLE_REMOTEPORT,
}CLIENT_TITLE_E;

#endif
